### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by architarious** [Snugug/generator-aurora#10]
When I try to install the generator on a windows machine I get a ton of errors, however when I install the generator on linux everything goes fine. I've tried this on 3 other machines running windows 8 and all three of them errored and failed, is this a huge fluke and am I the only one experiencing this? If not, are there any plans to expand this generator to windows? 

Thanks,
Architarious

**Comment by iamcarrico** [comment]
The generator is built to work with Yeoman's best practices, and I am unaware of any special code that needs to be written for Windows support. What errors are you getting? Also, what method did you use to get yeoman/bundler working on your windows machines?

**Comment by rogerrogers** [comment]
Yeah, doesn't work on Windows for me either. Shucks. I would paste the errors, but it's a lot of them, and I think this will fail on any Windows, so it's really just down to supporting installation on Windows.

**Comment by iamcarrico** [comment]
PRs are welcome, but at this time I don't have a windows machine to even attempt to test in.

**Comment by rogerrogers** [comment]
No worries, just wanted to confirm archiatarious' post. I'm playing with Zen, making it work with Singularity. Wanted to try Aurora, may come back to it yet. :)

**Comment by architarious** [comment]
Just for reference and sorry for the delay, I didn't notice you commented back until just now:

$ npm install -g yo generator-aurora
|

> execSync@1.0.2 install C:\Users\jsmith85\AppData\Roaming\npm\node_modules\gene
> rator-aurora\node_modules\execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
{ [Error: spawn ENOENT] code: 'ENOENT', errno: 'ENOENT', syscall: 'spawn' }
[execSync v1.0.2]
    Native code compile failed!!
    Will try to use win32 extension.
C:\Users\jsmith85\AppData\Roaming\npm\yo -> C:\Users\jsmith85\AppData\Roaming\np
m\node_modules\yo\cli.js

> yo@1.2.1 postinstall C:\Users\jsmith85\AppData\Roaming\npm\node_modules\yo
> node ./scripts/doctor

[Yeoman Doctor] Everything looks alright!

generator-aurora@0.2.7 C:\Users\jsmith85\AppData\Roaming\npm\node_modules\genera
tor-aurora
├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
├── underscore.string@2.3.3
├── execSync@1.0.2 (temp@0.5.1)
└── yeoman-generator@0.16.0 (dargs@0.1.0, diff@1.0.8, debug@0.7.4, class-extend@
0.1.1, rimraf@2.2.8, findup-sync@0.1.3, text-table@0.2.0, mime@1.2.11, async@0.2
.10, mkdirp@0.3.5, isbinaryfile@2.0.1, shelljs@0.2.6, glob@3.2.11, iconv-lite@0.
2.11, request@2.30.0, lodash@2.4.1, file-utils@0.1.5, download@0.1.19, cheerio@0
.13.1, inquirer@0.4.1)

yo@1.2.1 C:\Users\jsmith85\AppData\Roaming\npm\node_modules\yo
├── is-root@0.1.0
├── fullname@0.1.1
├── opn@0.1.2
├── async@0.9.0
├── sudo-block@0.4.0 (chalk@0.4.0)
├── multiline@0.3.4 (strip-indent@0.1.3)
├── nopt@3.0.1 (abbrev@1.0.5)
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.2, supports-color@0
.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── string-length@0.1.2 (strip-ansi@0.2.2)
├── findup@0.1.5 (commander@2.1.0, colors@0.6.2)
├── shelljs@0.3.0
├── yosay@0.3.0 (ansi-regex@0.2.1, ansi-styles@1.1.0, pad-component@0.0.1, word-
wrap@0.1.3, chalk@0.4.0, minimist@0.2.0, strip-ansi@0.2.2, taketalk@0.1.1)
├── lodash@2.4.1
├── update-notifier@0.2.1 (string-length@1.0.0, semver-diff@1.0.0, latest-versio
n@1.0.0, configstore@0.3.1)
├── insight@0.3.1 (object-assign@0.1.2, async@0.2.10, chalk@0.4.0, lodash.deboun
ce@2.4.1, request@2.27.0, inquirer@0.4.1, configstore@0.2.3)
└── yeoman-generator@0.17.6 (dargs@2.0.3, diff@1.0.8, class-extend@0.1.1, rimraf
@2.2.8, github-username@1.0.0, text-table@0.2.0, mime@1.2.11, cross-spawn@0.2.3,
 debug@1.0.4, run-async@0.1.0, grouped-queue@0.3.0, isbinaryfile@2.0.1, mkdirp@0
.5.0, iconv-lite@0.4.4, findup-sync@0.1.3, file-utils@0.2.1, underscore.string@2
.3.3, glob@4.0.6, cheerio@0.17.0, gruntfile-editor@0.2.0, request@2.44.0, downlo
ad@1.0.7, inquirer@0.7.3)

**Comment by iamcarrico** [comment]
This error is with the installation of Yeoman, you will have to go to their support to find the best way to install for Windows.
