### ISSUE TITLE
Problem with Gruntfile.js paths variable

### ISSUE THREAD

**Issue by adrianopulz** [Snugug/generator-aurora#13]
In this line: var paths = require('compass-options').paths(); the paths var get a full path, like sites/all/themes/theme_name/sass but need use de relative path like sass to "grunt watch" work. To fix this problem, I changed this line to: var paths = require('compass-options').dirs();

**Comment by iamcarrico** [comment]
Please open an issue / PR on https://github.com/frontend-united/generator-drupal-theme , where all active development is.

**Comment by adrianopulz** [comment]
Sorry, I'll move open it there. Thank you.
