### ISSUE TITLE
gulp watch: ReferenceError: i is not defined

### ISSUE THREAD

**Issue by adrianopulz** [Snugug/generator-aurora#14]
gulp watch return a error: ReferenceError: i is not defined
I checked de gulpfile.js and removed the "i" at this part of code, is the last caracter:

gulp.task('watch', function () {
  gulp.watch(paths.js + '/**/*.js', ['lint', 'scripts']);
  gulp.watch(paths.sass + '/**/*.scss', ['compass']);
});i

**Comment by iamcarrico** [comment]
Already fixed in frontend-united/generator-drupal-theme#13

**Comment by adrianopulz** [comment]
Perfect, thank you.
