### ISSUE TITLE
Missing functions/variables SCSS files.

### ISSUE THREAD

**Issue by fidelix** [Snugug/generator-aurora#2]
I got these errors running "gulp compass" right after scaffolding

error sass/style.scss (Line 21 of sass/partials/global/_base.scss: File to import not found or unreadable: functions.
error sass/print.scss (Line 20 of sass/partials/global/_base.scss: File to import not found or unreadable: variables.

I believe these files were supposed to be generated automatically, even if empty...

**Comment by Snugug** [comment]
What Aurora subtheme type did you use?

**Comment by fidelix** [comment]
Aurora

**Comment by iamcarrico** [comment]
Working on a fix currently. The Most recent commits fixes it for Corona.

**Comment by iamcarrico** [comment]
Fixed, pushing to npm this morning.

**Comment by aliyakhan** [comment]
This goes same for Polaris as well.

**Comment by iamcarrico** [comment]
Should be fixed, the files are not present, but the imports are commented out. We did this so that you could use whatever structure you desire, and those files would be empty anyway.
