### ISSUE TITLE
Can't @import normalize

### ISSUE THREAD

**Issue by jantoine1** [Snugug/generator-aurora#6]
Uncommenting '@import normalize' in _style-guies.scss results in the following error:
<code>
error sass/style.scss (Line 19 of sass/partials/styleguide/_style-guide.scss: File to import not found or unreadable: normalize.
</code>

This seems to be due to the fact that the 'compass-normalize' gem has been removed from the project. To fix this, I had to do the following:
- Add "gem 'compass-normalize', '~> 1.5'" to Gemfile
- Add "require 'compass-normalize'" to config.rb
- Run "bundle update" on command line

**Comment by iamcarrico** [comment]
Yes--- we are no longer suggesting people use normalize in this fashion, as Normalize is meant to be altered to be how you want the "base" styles to be. 

As a note: currently 'compass-normalize' does NOT work with Compass 1.0, you will need version 2.0, which is only in their GitHub repo, not on RubyGems.
